### Autostart ###

# Polkit agent
exec-once = /usr/libexec/polkit-kde-authentication-agent-1

# UI
exec-once = waybar
exec-once = $SCRIPTS/theming/apply_wallpaper.sh

# Idle service
exec-once = hypridle

# Audio daemons
exec-once = pipewire
exec-once = playerctld

# Clipboard
exec-once = wl-clip-persist --clipboard regular

# Misc daemons
exec-once = udiskie
exec-once = transmission-daemon
