### Rules ###

# Disable maximizing
windowrulev2 = suppressevent maximize, class:.*
# Disable idle behavior when fullscreen
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1
# Open Thunderbird in workspace 6
windowrulev2 = workspace 6, class:^Thunderbird$
