### Rules ###

# Disable maximizing
windowrulev2 = suppressevent maximize, class:.*

# Disable idle behavior when fullscreen
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

# Open musikcube in workspace 5 as small pseudo window
windowrulev2 = workspace 5, initialtitle:^musikcube$
windowrulev2 = pseudo, initialtitle:^musikcube$
windowrulev2 = size 65% 60%, initialtitle:^musikcube$

# Open Thunderbird in workspace 6
windowrulev2 = workspace 6, class:^Thunderbird$
